### ISSUE TITLE
Demo and Running code on my own shows just loading square 

### ISSUE THREAD

**Issue by tzb02** [dvikas/nextjs-graphql-adminpanel#2]
Demo and Running code on my own shows just loading square, and then the page is blank

**Comment by dvikas** [comment]
Hi, 
On Local 
front end URL should be `http://local.app.nextgraphqladmin.com:3000` and 
back end URL should be `https://local.api.nextgraphqladmin.com:4000` (here you should be able to see GraphQL playground)

Also please check `Browser's developer tools -> Console` for any error 

Follow [install instructions](https://github.com/dvikas/nextjs-graphql-adminpanel/tree/main/api) carefully.
